{
 "title": "Ads Statistics",
 "time": { "from": "2025-02-16T01:26:12.394Z", "to": "2025-02-16T13:26:12.394Z" },
 "templating": {
  "list": [
   {
    "name": "CampaignID",
    "query": "79358b6a-27c7-40d1-9544-fca5f67db670"
   },
   {
    "name": "AdvertiserID",
    "query": "0194fa47-2245-78b4-a755-60e8f8874d74"
   },
   { "name": "Database", "query": "grafana-postgresql-datasource" }
  ]
 },
 "panels": [
  {
   "title": "Stats By Campaign ID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH impr_stats AS (SELECT campaign_id,\r\n                           SUM(cost) AS spent_impressions\r\n                    FROM impressions\r\n                    WHERE campaign_id = ${CampaignID:singlequote} \r\n                    GROUP BY campaign_id),\r\n     click_stats AS (SELECT campaign_id,\r\n                            SUM(cost) AS spent_clicks\r\n                     FROM clicks\r\n                     WHERE campaign_id = ${CampaignID:singlequote}\r\n                     GROUP BY campaign_id)\r\nSELECT c.impressions_count,\r\n       c.clicks_count,\r\n       COALESCE((c.clicks_count::numeric / NULLIF(c.impressions_count, 0)) * 100, 0)     AS conversion,\r\n       COALESCE(impr_stats.spent_impressions, 0)                                         AS spent_impressions,\r\n       COALESCE(click_stats.spent_clicks, 0)                                             AS spent_clicks,\r\n       COALESCE(impr_stats.spent_impressions, 0) + COALESCE(click_stats.spent_clicks, 0) AS spent_total\r\nFROM campaigns c\r\n         LEFT JOIN impr_stats ON c.id = impr_stats.campaign_id\r\n         LEFT JOIN click_stats ON c.id = click_stats.campaign_id\r\nWHERE c.id = ${CampaignID:singlequote};"
    }
   ]
  },
  {
   "title": "Stats By Advertiser ID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH impr_stats AS (SELECT c.advertiser_id,\r\n                           COUNT(*)    AS total_impressions,\r\n                           SUM(i.cost) AS spent_impressions\r\n                    FROM impressions i\r\n                             JOIN campaigns c ON i.campaign_id = c.id\r\n                    WHERE c.advertiser_id = ${AdvertiserID:singlequote}\r\n                    GROUP BY c.advertiser_id),\r\n     click_stats AS (SELECT c.advertiser_id,\r\n                            COUNT(*)     AS total_clicks,\r\n                            SUM(c2.cost) AS spent_clicks\r\n                     FROM clicks c2\r\n                              JOIN campaigns c ON c2.campaign_id = c.id\r\n                     WHERE c.advertiser_id = ${AdvertiserID:singlequote}\r\n                     GROUP BY c.advertiser_id)\r\nSELECT COALESCE(impr_stats.total_impressions, 0)                                         AS impressions_count,\r\n       COALESCE(click_stats.total_clicks, 0)                                             AS clicks_count,\r\n       COALESCE(\r\n               (click_stats.total_clicks::numeric / NULLIF(impr_stats.total_impressions, 0)) * 100,\r\n               0\r\n       )                                                                                 AS conversion,\r\n       COALESCE(impr_stats.spent_impressions, 0)                                         AS spent_impressions,\r\n       COALESCE(click_stats.spent_clicks, 0)                                             AS spent_clicks,\r\n       COALESCE(impr_stats.spent_impressions, 0) + COALESCE(click_stats.spent_clicks, 0) AS spent_total\r\nFROM impr_stats\r\n         FULL OUTER JOIN click_stats USING (advertiser_id)"
    }
   ]
  },
  {
   "title": "Daily Stats by CampaignID",
   "type": "trend",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(imps.impressions_count, 0)                                  AS impressions_count,\r\n       COALESCE(clks.clicks_count, 0)                                       AS clicks_count,\r\n       COALESCE(\r\n               (clks.clicks_count::numeric / NULLIF(imps.impressions_count, 0)) * 100,\r\n               0\r\n       )                                                                    AS conversion,\r\n       COALESCE(imps.spent_impressions, 0)                                  AS spent_impressions,\r\n       COALESCE(clks.spent_clicks, 0)                                       AS spent_clicks,\r\n       COALESCE(imps.spent_impressions, 0) + COALESCE(clks.spent_clicks, 0) AS spent_total,\r\n       COALESCE(imps.day, clks.day)                                         AS day\r\nFROM campaigns c\r\n         LEFT JOIN (SELECT campaign_id,\r\n                           day,\r\n                           COUNT(*)  AS impressions_count,\r\n                           SUM(cost) AS spent_impressions\r\n                    FROM impressions\r\n                    WHERE campaign_id = ${CampaignID:singlequote}\r\n                    GROUP BY campaign_id, day) imps ON c.id = imps.campaign_id\r\n         LEFT JOIN (SELECT campaign_id,\r\n                           day,\r\n                           COUNT(*)  AS clicks_count,\r\n                           SUM(cost) AS spent_clicks\r\n                    FROM clicks\r\n                    WHERE campaign_id = ${CampaignID:singlequote}\r\n                    GROUP BY campaign_id, day) clks ON c.id = clks.campaign_id\r\nWHERE c.id = ${CampaignID:singlequote}\r\n  AND COALESCE(imps.day, clks.day) IS NOT NULL\r\nORDER BY COALESCE(imps.day, clks.day);"
    }
   ]
  },
  {
   "title": "Daily Stats by AdvertiserID",
   "type": "trend",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT COALESCE(SUM(imps.impressions_count), 0)                          AS impressions_count,\r\n       COALESCE(SUM(clks.clicks_count), 0)                               AS clicks_count,\r\n       COALESCE(\r\n               (SUM(clks.clicks_count)::numeric / NULLIF(SUM(imps.impressions_count), 0)) * 100,\r\n               0\r\n       )                                                                 AS conversion,\r\n       COALESCE(SUM(imps.spent_impressions), 0)                          AS spent_impressions,\r\n       COALESCE(SUM(clks.spent_clicks), 0)                               AS spent_clicks,\r\n       COALESCE(SUM(imps.spent_impressions) + SUM(clks.spent_clicks), 0) AS spent_total,\r\n       COALESCE(imps.day, clks.day)                                      AS day\r\nFROM campaigns c\r\n         LEFT JOIN (SELECT campaign_id,\r\n                           day,\r\n                           COUNT(*)  AS impressions_count,\r\n                           SUM(cost) AS spent_impressions\r\n                    FROM impressions\r\n                    GROUP BY campaign_id, day) imps ON c.id = imps.campaign_id\r\n         LEFT JOIN (SELECT campaign_id,\r\n                           day,\r\n                           COUNT(*)  AS clicks_count,\r\n                           SUM(cost) AS spent_clicks\r\n                    FROM clicks\r\n                    GROUP BY campaign_id, day) clks ON c.id = clks.campaign_id\r\nWHERE c.advertiser_id = ${AdvertiserID:singlequote}\r\n  AND COALESCE(imps.day, clks.day) IS NOT NULL\r\nGROUP BY COALESCE(imps.day, clks.day)\r\nORDER BY COALESCE(imps.day, clks.day);"
    }
   ]
  }
 ]
}