service: # изменять в случае изменений в .env
  backend:
    certificate:
      cert-file: "/etc/letsencrypt/live/npm-1/fullchain.pem"
      key-file: "/etc/letsencrypt/live/npm-1/privkey.pem"

    port: 3000

  database:
    ssl-mode: "disable"

settings:
  debug: true # включение / выключение дебага
  listen-tls: false # false - http, true - https (при первом старте до выпуска сертификатов - ставить false, после - true)
  timezone: "GMT+3" # часовой пояс в формате "GMT+3"
  moderation: false
  body-size-limit: 10 # Лимит размера тела запроса в мегабайтах (в основном относится к картинкам)